### ISSUE TITLE
Add command to make local user an admin

### ISSUE THREAD

**Issue by mforner13** [uktrade/update-supply-chain-information#114]
When working locally, in order to make yourself an admin user you need to do the following:

1. Access the app, so that you are added in the database as a user (taking details from staff-sso)
2. Open a django shell
3. Find yourself in the User table
4. Set `is_staff` and `is_superuser` as True and save() your user object

It would be really useful to have a command (perhaps make command) which would set yourself as an admin.

**Comment by dev-digital** [comment]
Added admin command _local_admin_ as part of #226
