### ISSUE TITLE
New DIT users unable to log in

### ISSUE THREAD

**Issue by NickFitz** [uktrade/update-supply-chain-information#231]
The `xWhitehall` dummy department, which is needed by supply chains that don't have an owning department, has the same email domains as DIT. The user's email domain is used to determine which department they belong to when they access the service. As both of these departments have the same email domains, a user from DIT logging in to the service for the first time will be met with a `GovDepartment.MultipleObjectsReturned` error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to access the service as a user with a DIT email address that has never previously done so.
2. See error `GovDepartment.MultipleObjectsReturned`.

**Expected behaviour**
An instance of `accounts.models.User` is created with the user's login details and DIT as their `accounts.models.GovDepartment`.

**Additional context**
The `accounts.test.test_auth.test_two_departments_with_same_email_domain_prevents_login` test will pass while this issue is unresolved. It should be marked as expected to fail once the issue is resolved.

The `accounts.test.test_auth.test_two_departments_with_same_email_domain_does_not_prevent_login` test will pass when this issue has been resolved. It is currently marked as expected to fail.

**Proposed fix**
In the function `accounts.models.get_gov_department_id_from_user_email`, modify the line
```python
return GovDepartment.objects.get(email_domains__contains=[domain])
```
to exclude the unwanted department:
```python
return GovDepartment.objects.exclude(name="xWhitehall").get(email_domains__contains=[domain])
```

**Comment by dev-digital** [comment]
This is not a bug anymore as email domains for departments happen to be unique :grinning:
